#!/usr/bin/env bash
echo "1. Test that we can parse a pipe delimited file"
IN="tests/invoicing-pipe-delimited.csv"
OUT="tests/scrubbed_invoicing-pipe-delimited.csv"
REF="tests/reference_invoicing-pipe-delimited.csv"
scrub "$IN" > "$OUT"
if cmp "$OUT" "$REF"; then
    echo -e "SUCCESS ✔: $OUT == $REF \n\n"
else
    echo -e "FAIL ✘: \n\n"
fi

echo "2. Test that we can parse a pipe delimited file when skipping comment before header"
IN="tests/invoicing-pipe-delimited-with-comments.csv"
OUT="tests/scrubbed_invoicing-pipe-delimited-with-comments.csv"
REF="tests/reference_invoicing-pipe-delimited.csv"
scrub --skip-lines=1 "$IN" > "$OUT"
if cmp "$OUT" "$REF"; then
    echo -e "SUCCESS ✔: $OUT == $REF \n\n"
else
    echo -e "FAIL ✘: \n\n"
fi

echo "3. Test that we can parse a tab delimited file"
IN="tests/invoicing-tab-delimited.tsv"
OUT="tests/scrubbed_invoicing-tab-delimited.csv"
REF="tests/reference_invoicing-tab-delimited.csv"
scrub "$IN" > "$OUT"
if cmp "$OUT" "$REF"; then
    echo -e "SUCCESS ✔: $OUT == $REF \n\n"
else
    echo -e "FAIL ✘: \n\n"
fi

echo "4. Test that we can parse a binary excel file"
IN="tests/invoicing.xls"
OUT="tests/scrubbed_invoicing.csv"
REF="tests/reference_invoicing.csv"
scrub "$IN" > "$OUT"
if cmp "$OUT" "$REF"; then
    echo -e "SUCCESS ✔: $OUT == $REF \n\n"
else
    echo -e "FAIL ✘: \n\n"
fi

echo "5. Test that we can parse an .xml excel file"
IN="tests/invoicing.xlsx"
OUT="tests/scrubbed_invoicing.csv"
REF="tests/reference_invoicing.csv"
scrub "$IN" > "$OUT"
if cmp "$OUT" "$REF"; then
    echo -e "SUCCESS ✔: $OUT == $REF \n\n"
else
    echo -e "FAIL ✘: \n\n"
fi

echo "6. Test that we can parse an openoffice excel file"
IN="tests/invoicing-openoffice-format.xlsx"
OUT="tests/scrubbed_invoicing.csv"
REF="tests/reference_invoicing.csv"
scrub "$IN" > "$OUT"
if cmp "$OUT" "$REF"; then
    echo -e "SUCCESS ✔: $OUT == $REF \n\n"
else
    echo -e "FAIL ✘: \n\n"
fi

echo "7. Test that using option -f (schema file) works with file containing trailing backslash in first field"
IN="tests/invoicing-trailing-backslash.csv"
SCHEMA="tests/invoicing-trailing-backslash.csv.metadata"
OUT="tests/scrubbed_invoicing-trailing-backslash.csv"
REF="tests/reference_invoicing-trailing-backslash.csv"
scrub -f "$SCHEMA" "$IN" > "$OUT"
if cmp "$OUT" "$REF"; then
    echo -e "SUCCESS ✔: $OUT == $REF \n\n"
else
    echo -e "FAIL ✘: \n\n"
fi

echo "8. Test that using option -f (schema file) errors out when the schema file contains incorrect data types"
IN="tests/invoicing-trailing-backslash.csv"
SCHEMA="tests/bad-data-types_invoicing-trailing-backslash.csv.metadata"
OUT="tests/scrubbed_bad-data-types_invoicing-trailing-backslash.csv"
REF="tests/reference_bad-data-types_invoicing-trailing-backslash.csv"
scrub -f "$SCHEMA" "$IN" > "$OUT"
if cmp "$OUT" "$REF"; then
    echo -e "SUCCESS ✔: $OUT == $REF \n\n"
else
    echo -e "FAIL ✘: \n\n"
fi

echo "9. Test that using option -n (NA values) with a single NA value works"
IN="tests/invoicing-with-na-value.csv"
OUT="tests/scrubbed_invoicing-with-na-value.csv"
REF="tests/reference_invoicing-with-na-value.csv"
scrub -n "NA" "$IN" > "$OUT"
if cmp "$OUT" "$REF"; then
    echo -e "SUCCESS ✔: $OUT == $REF \n\n"
else
    echo -e "FAIL ✘: \n\n"
fi

echo "10. Test that using option -n (NA values) with a multiple NA values works"
IN="tests/invoicing-with-many-na-values.csv"
OUT="tests/scrubbed_invoicing-with-many-na-values.csv"
REF="tests/reference_invoicing-with-many-na-values.csv"
scrub -n "NA;0000-00-00T00:00:00Z" "$IN" > "$OUT"
if cmp "$OUT" "$REF"; then
    echo -e "SUCCESS ✔: $OUT == $REF \n\n"
else
    echo -e "FAIL ✘: \n\n"
fi
echo "11. Test that using option -q (quote) in combination with option -b (escape backslashes) works"
IN="tests/invoicing-with-single-quotes.csv"
OUT="tests/scrubbed_invoicing-with-single-quotes.csv"
REF="tests/reference_invoicing-with-single-quotes.csv"
scrub -q "'" -b "$IN" > "$OUT"
if cmp "$OUT" "$REF"; then
    echo -e "SUCCESS ✔: $OUT == $REF \n\n"
else
    echo -e "FAIL ✘: \n\n"
fi

# clean up
rm tests/scrubbed_*
