#!/usr/bin/env bash

echo "1. Test that we can load a .tsv file into a sqlite database"
IN="tests/scrubbed_invoicing.tsv"
OUT="tests/sqlite.db"
REF="tests/reference_sqlite.db"
load "sqlite://${OUT}" "$IN"
if cmp "$OUT" "$REF"; then
    echo -e "SUCCESS ✔: $OUT == $REF \n\n"
else
    echo -e "FAIL ✘: \n\n"
fi

# perform clean up
rm tests/sqlite.db
