#!/usr/bin/env bash

echo "1. Test that we can load a .tsv file into a sqlite database"
IN="tests/scrubbed_invoicing.tsv"
METADATA="tests/scrubbed_invoicing.metadata"
OUT="tests/sqlite.db"
REF="tests/reference_sqlite.db"
load -f tests/.env "$IN" "$METADATA"
if cmp "$OUT" "$REF"; then
    echo -e "SUCCESS ✔: $OUT == $REF \n\n"
else
    echo -e "FAIL ✘: \n\n"
fi

# perform clean up
rm tests/sqlite.db
