# This file has been generated by node2nix 1.8.0. Do not edit!

{ nodeEnv, fetchurl, fetchgit, globalBuildInputs ? [ ] }:

let
  sources = {
    "ansi-regex-2.1.1" = {
      name = "ansi-regex";
      packageName = "ansi-regex";
      version = "2.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ansi-regex/-/ansi-regex-2.1.1.tgz";
        sha1 = "c3b33ab5ee360d86e0e628f0468ae7ef27d654df";
      };
    };
    "csv-5.3.1" = {
      name = "csv";
      packageName = "csv";
      version = "5.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/csv/-/csv-5.3.1.tgz";
        sha512 =
          "UBO4x5EYpihikfjHUQ7dCTIgC+e9TrWWZbCcoMr935tcAZfXT1MZKHLD+aYSHs1jwW2G1uljpFfJ4XxYwQ6t5w==";
      };
    };
    "csv-generate-3.3.0" = {
      name = "csv-generate";
      packageName = "csv-generate";
      version = "3.3.0";
      src = fetchurl {
        url =
          "https://registry.npmjs.org/csv-generate/-/csv-generate-3.3.0.tgz";
        sha512 =
          "EXSru4QwEWKwM7wwsJbhrZC+mHEJrhQFoXlohHs80CAU8Qhlv9gaw1sjzNiC3Hr3oUx5skDmEiAlz+tnKWV0RA==";
      };
    };
    "csv-parse-4.15.1" = {
      name = "csv-parse";
      packageName = "csv-parse";
      version = "4.15.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/csv-parse/-/csv-parse-4.15.1.tgz";
        sha512 =
          "TXIvRtNp0fqMJbk3yPR35bQIDzMH4khDwduElzE7Fl1wgnl25mnWYLSLqd/wS5GsDoX1rWtysivEYMNsz5jKwQ==";
      };
    };
    "csv-stringify-5.6.1" = {
      name = "csv-stringify";
      packageName = "csv-stringify";
      version = "5.6.1";
      src = fetchurl {
        url =
          "https://registry.npmjs.org/csv-stringify/-/csv-stringify-5.6.1.tgz";
        sha512 =
          "JlQlNZMiuRGSFbLXFNGoBtsORXlkqf4Dfq8Ee0Jo4RVJj3YAUzevagUx24mDrQJLDF7aYz6Ne8kqA8WWBaYt2A==";
      };
    };
    "faker-git://github.com/Marak/faker.js" = {
      name = "faker";
      packageName = "faker";
      version = "5.3.1";
      src = fetchgit {
        url = "git://github.com/Marak/faker.js";
        rev = "5478d65dcb99a3c5f1a941d6a9d101d02bc467c2";
        sha256 =
          "4089e4bd1b079e6bf80ef22f7c35d9bd2fbe0c65c36561281aa7c11f9bd39a23";
      };
    };
    "lodash-4.17.15" = {
      name = "lodash";
      packageName = "lodash";
      version = "4.17.15";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash/-/lodash-4.17.15.tgz";
        sha512 =
          "8xOcRHvCjnocdS5cpwXQXVzmmh5e5+saE2QGoeQmbKmRS6J3VQppPOIt0MnmE+4xlZoumy0GPG0D0MVIQbNA1A==";
      };
    };
    "mixme-0.4.0" = {
      name = "mixme";
      packageName = "mixme";
      version = "0.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/mixme/-/mixme-0.4.0.tgz";
        sha512 =
          "B4Sm1CDC5+ov5AYxSkyeT5HLtiDgNOLKwFlq34wr8E2O3zRdTvQiLzo599Jt9cir6VJrSenOlgvdooVYCQJIYw==";
      };
    };
    "neodoc-2.0.2" = {
      name = "neodoc";
      packageName = "neodoc";
      version = "2.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/neodoc/-/neodoc-2.0.2.tgz";
        sha512 =
          "NAppJ0YecKWdhSXFYCHbo6RutiX8vOt/Jo3l46mUg6pQlpJNaqc5cGxdrW2jITQm5JIYySbFVPDl3RrREXNyPw==";
      };
    };
    "stream-transform-2.0.4" = {
      name = "stream-transform";
      packageName = "stream-transform";
      version = "2.0.4";
      src = fetchurl {
        url =
          "https://registry.npmjs.org/stream-transform/-/stream-transform-2.0.4.tgz";
        sha512 =
          "LQXH1pUksoef5Ijo6+2ihnjLLZtZuoqu1vhut6a7xZ77nrLA/shbbx2FAzVC/nkb6wwrPzOO98700mv4HDQcWg==";
      };
    };
  };
  args = {
    name = "anonymize";
    packageName = "anonymize";
    version = "0.2.0";
    src = ./.;
    dependencies = [
      sources."ansi-regex-2.1.1"
      sources."csv-5.3.1"
      sources."csv-generate-3.3.0"
      sources."csv-parse-4.15.1"
      sources."csv-stringify-5.6.1"
      sources."faker-git://github.com/Marak/faker.js"
      sources."lodash-4.17.15"
      sources."mixme-0.4.0"
      sources."neodoc-2.0.2"
      sources."stream-transform-2.0.4"
    ];
    buildInputs = globalBuildInputs;
    meta = { license = "MIT"; };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
in {
  args = args;
  sources = sources;
  tarball = nodeEnv.buildNodeSourceDist args;
  package = nodeEnv.buildNodePackage args;
  shell = nodeEnv.buildNodeShell args;
}
