#!/usr/bin/env bash

# Purge any keypairs in .lassoer/
rm -rf ~/.lassoer

echo -n "1. Test that nothing gets written to .lassoer on incorrectly "
echo -e "entered password during the first age-keygen\n" 
archive -c .lassoer testdir
if [ ! -f '.lassoer/sd@signavio.com_age.priv' ] && [ ! -f '.lassoer/sd@signavio.com_age.pub' ]; then
    echo -e "SUCCESS ✔: nothing gets written to .lassoer\n\n"
else
    echo -e "FAIL ✘: \n\n"
fi

echo -n "2. Test that nothing gets written to .lassoer on incorrectly entered "
echo "password after being prompted to save password in password manager" 
archive -c .lassoer testdir
if [ ! -f '.lassoer/sd@signavio.com_age.priv' ] && [ ! -f '.lassoer/sd@signavio.com_age.pub' ]; then
    echo -e "SUCCESS ✔: nothing gets written to .lassoer\n\n"
else
    echo -e "FAIL ✘: \n\n"
fi

echo "3. Test that archiving (compress then encrypt) works"
archive -c .lassoer testdir
if [ -f 'testdir.tar.gz.age' ]; then
    echo -e "SUCCESS ✔: testdir archived to testdir.tar.gz.age\n\n"
else
    echo -e "FAIL ✘: \n\n"
fi

echo "4. Test that archiving also deletes input file/folder on user's request"
cp -r testdir testdir.bak
archive -c .lassoer testdir
if [ ! -d 'testdir' ]; then
    echo -e "SUCCESS ✔: input folder testdir deleted as per user's request\n\n"
    mv testdir.bak testdir
else
    echo -e "FAIL ✘: \n\n"
fi

echo "5. Test that archiving does not delete input file/folder on user's request"
archive -c .lassoer testdir
if [ -d 'testdir' ]; then
    echo -e "SUCCESS ✔: input folder testdir not deleted as per user's request\n\n"
else
    echo -e "FAIL ✘: \n\n"
fi

echo "6. Test that unarchiving (uncompress and decrypt) works"
if [ -d 'testdir' ]; then
    rm -rf testdir
fi
archive -c .lassoer -x testdir.tar.gz.age
if [ -d 'testdir' ]; then
    echo -e "SUCCESS ✔: unarchived testdir.tar.gz.age to testdir\n\n"
else
    echo -e "FAIL ✘: \n\n"
fi

echo "7. Test that nothing gets written to .lassoer on SIGINT (Control+C)"
rm -rf .lassoer
archive -c .lassoer testdir
if [ ! -f '.lassoer/sd@signavio.com_age.priv' ] && [ ! -f '.lassoer/sd@signavio.com_age.pub' ]; then
    echo -e "SUCCESS ✔: nothing gets written to .lassoer\n\n"
else
    echo -e "FAIL ✘: \n\n"
fi

# Cleanup
rm -rf .lassoer
