#!/usr/bin/env python
import multiprocessing
from optparse import OptionParser
from pathlib import Path
from dotenv import dotenv_values
from joblib import Parallel

num_cores = multiprocessing.cpu_count()
parser = OptionParser(
    usage="%prog [options] file...\n\nLoad CSV files into a sql database",
    version="%prog v0.3.0"
)
parser.add_option("-d", "--drop-schema", dest="drop_schema", action="store_true",
                  help="Drop existing database schema before create")
parser.add_option("-f", "--environment-file", dest="environment_file",
                  help="Location of environment file containing credentials",
                  default=Path('.') / '.env')
parser.add_option("-s", "--db-schema", dest="db_schema", type="string",
                  help="The database schema to load .csv files into")
parser.add_option("-t", "--type", dest="db_type", type="string", default="postgresql",
                  help="Type of sql database (postgresql or athena)")
(options, args) = parser.parse_args()

def print_arg(arg):
    print(f"arg: {arg}")
    
def run():
    Parallel(n_jobs=num_cores)(delayed(print_arg)(i) for i in args)

if __name__ == "__main__":
    run()
