#!/usr/bin/env bash

echo "1. Test that inspect guesses at the .csv file's schema properly"
IN="tests/scrubbed_invoicing.tsv"
OUT="tests/scrubbed_invoicing.tsv.metadata"
REF="tests/reference_invoicing.tsv.metadata"
inspect "$IN" > "$OUT"
if cmp "$OUT" "$REF"; then
    echo -e "SUCCESS ✔: $OUT == $REF \n\n"
else
    echo -e "FAIL ✘: \n\n"
fi

echo "2. Test option -u recognizes locale specific numeric columns"
IN="tests/bseg-anonymized-with-options.tsv"
OUT="tests/bseg-option-u.tsv.metadata"
REF="tests/reference_bseg-option-u.tsv.metadata"
inspect -u "8'999.99" "$IN" > "$OUT"
if cmp "$OUT" "$REF"; then
    echo -e "SUCCESS ✔: $OUT == $REF \n\n"
else
    echo -e "FAIL ✘: \n\n"
fi

echo "3. Test option -d recognizes locale specific date columns"
IN="tests/bseg-anonymized-with-options.tsv"
OUT="tests/bseg-option-d.tsv.metadata"
REF="tests/reference_bseg-option-d.tsv.metadata"
inspect -d '01-02-2006' "$IN" > "$OUT"
if cmp "$OUT" "$REF"; then
    echo -e "SUCCESS ✔: $OUT == $REF \n\n"
else
    echo -e "FAIL ✘: \n\n"
fi

echo "4. Test option -n converts na values to an empty string"
IN="tests/bseg-anonymized-with-options.tsv"
OUT="tests/bseg-option-n.tsv.metadata"
REF="tests/reference_bseg-option-n.tsv.metadata"
inspect -d '01-02-2006' -n '00-00-0000' "$IN" > "$OUT"
if cmp "$OUT" "$REF"; then
    echo -e "SUCCESS ✔: $OUT == $REF \n\n"
else
    echo -e "FAIL ✘: \n\n"
fi

# Perform clean-up
rm tests/bseg-*tsv.metadata
